# coding: utf-8

"""
    OpenAPI for NCATS Biomedical Translator Reasoners

    OpenAPI for NCATS Biomedical Translator Reasoners  # noqa: E501

    The version of the OpenAPI document: 0.9.2
    Contact: edeutsch@systemsbiology.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.predicates_api import PredicatesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPredicatesApi(unittest.TestCase):
    """PredicatesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.predicates_api.PredicatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_predicates_get(self):
        """Test case for predicates_get

        Get supported relationships by source and target  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
