# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class NodeBinding(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, kg_id=None):  # noqa: E501
        """NodeBinding - a model defined in OpenAPI

        :param kg_id: The kg_id of this NodeBinding.  # noqa: E501
        :type kg_id: str
        """
        self.openapi_types = {
            'kg_id': str
        }

        self.attribute_map = {
            'kg_id': 'kg_id'
        }

        self._kg_id = kg_id

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NodeBinding of this NodeBinding.  # noqa: E501
        :rtype: NodeBinding
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kg_id(self):
        """Gets the kg_id of this NodeBinding.

        A knowledge-graph node id, i.e. the `id` of a KNode  # noqa: E501

        :return: The kg_id of this NodeBinding.
        :rtype: str
        """
        return self._kg_id

    @kg_id.setter
    def kg_id(self, kg_id):
        """Sets the kg_id of this NodeBinding.

        A knowledge-graph node id, i.e. the `id` of a KNode  # noqa: E501

        :param kg_id: The kg_id of this NodeBinding.
        :type kg_id: str
        """
        if kg_id is None:
            raise ValueError("Invalid value for `kg_id`, must not be `None`")  # noqa: E501

        self._kg_id = kg_id
