# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.one_ofstringarray import OneOfstringarray
from openapi_server import util

from openapi_server.models.one_ofstringarray import OneOfstringarray  # noqa: E501

class QNode(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, curie=None, type=None):  # noqa: E501
        """QNode - a model defined in OpenAPI

        :param curie: The curie of this QNode.  # noqa: E501
        :type curie: OneOfstringarray
        :param type: The type of this QNode.  # noqa: E501
        :type type: OneOfstringarray
        """
        self.openapi_types = {
            'curie': OneOfstringarray,
            'type': OneOfstringarray
        }

        self.attribute_map = {
            'curie': 'curie',
            'type': 'type'
        }

        self._curie = curie
        self._type = type

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QNode of this QNode.  # noqa: E501
        :rtype: QNode
        """
        return util.deserialize_model(dikt, cls)

    @property
    def curie(self):
        """Gets the curie of this QNode.

        CURIE identifier for this node  # noqa: E501

        :return: The curie of this QNode.
        :rtype: OneOfstringarray
        """
        return self._curie

    @curie.setter
    def curie(self, curie):
        """Sets the curie of this QNode.

        CURIE identifier for this node  # noqa: E501

        :param curie: The curie of this QNode.
        :type curie: OneOfstringarray
        """

        self._curie = curie

    @property
    def type(self):
        """Gets the type of this QNode.


        :return: The type of this QNode.
        :rtype: OneOfstringarray
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this QNode.


        :param type: The type of this QNode.
        :type type: OneOfstringarray
        """

        self._type = type
