# coding: utf-8

"""
    OpenAPI for NCATS Biomedical Translator Reasoners

    OpenAPI for NCATS Biomedical Translator Reasoners  # noqa: E501

    The version of the OpenAPI document: 0.9.2
    Contact: edeutsch@systemsbiology.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class EdgeBinding(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'kg_id': 'str'
    }

    attribute_map = {
        'kg_id': 'kg_id'
    }

    def __init__(self, kg_id=None, local_vars_configuration=None):  # noqa: E501
        """EdgeBinding - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._kg_id = None
        self.discriminator = None

        self.kg_id = kg_id

    @property
    def kg_id(self):
        """Gets the kg_id of this EdgeBinding.  # noqa: E501

        A knowledge-graph edge id, i.e. the `id` of a KEdge  # noqa: E501

        :return: The kg_id of this EdgeBinding.  # noqa: E501
        :rtype: str
        """
        return self._kg_id

    @kg_id.setter
    def kg_id(self, kg_id):
        """Sets the kg_id of this EdgeBinding.

        A knowledge-graph edge id, i.e. the `id` of a KEdge  # noqa: E501

        :param kg_id: The kg_id of this EdgeBinding.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and kg_id is None:  # noqa: E501
            raise ValueError("Invalid value for `kg_id`, must not be `None`")  # noqa: E501

        self._kg_id = kg_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EdgeBinding):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EdgeBinding):
            return True

        return self.to_dict() != other.to_dict()
