# coding: utf-8

"""
    OpenAPI for NCATS Biomedical Translator Reasoners

    OpenAPI for NCATS Biomedical Translator Reasoners  # noqa: E501

    The version of the OpenAPI document: 0.9.2
    Contact: edeutsch@systemsbiology.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class Message(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'results': 'list[Result]',
        'query_graph': 'QueryGraph',
        'knowledge_graph': 'KnowledgeGraph'
    }

    attribute_map = {
        'results': 'results',
        'query_graph': 'query_graph',
        'knowledge_graph': 'knowledge_graph'
    }

    def __init__(self, results=None, query_graph=None, knowledge_graph=None, local_vars_configuration=None):  # noqa: E501
        """Message - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._results = None
        self._query_graph = None
        self._knowledge_graph = None
        self.discriminator = None

        if results is not None:
            self.results = results
        if query_graph is not None:
            self.query_graph = query_graph
        if knowledge_graph is not None:
            self.knowledge_graph = knowledge_graph

    @property
    def results(self):
        """Gets the results of this Message.  # noqa: E501

        List of all returned potential answers for the query posed  # noqa: E501

        :return: The results of this Message.  # noqa: E501
        :rtype: list[Result]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this Message.

        List of all returned potential answers for the query posed  # noqa: E501

        :param results: The results of this Message.  # noqa: E501
        :type: list[Result]
        """

        self._results = results

    @property
    def query_graph(self):
        """Gets the query_graph of this Message.  # noqa: E501


        :return: The query_graph of this Message.  # noqa: E501
        :rtype: QueryGraph
        """
        return self._query_graph

    @query_graph.setter
    def query_graph(self, query_graph):
        """Sets the query_graph of this Message.


        :param query_graph: The query_graph of this Message.  # noqa: E501
        :type: QueryGraph
        """

        self._query_graph = query_graph

    @property
    def knowledge_graph(self):
        """Gets the knowledge_graph of this Message.  # noqa: E501


        :return: The knowledge_graph of this Message.  # noqa: E501
        :rtype: KnowledgeGraph
        """
        return self._knowledge_graph

    @knowledge_graph.setter
    def knowledge_graph(self, knowledge_graph):
        """Sets the knowledge_graph of this Message.


        :param knowledge_graph: The knowledge_graph of this Message.  # noqa: E501
        :type: KnowledgeGraph
        """

        self._knowledge_graph = knowledge_graph

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Message):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Message):
            return True

        return self.to_dict() != other.to_dict()
