openapi: 3.0.1
info:
  contact:
    email: edeutsch@systemsbiology.org
  description: OpenAPI for NCATS Biomedical Translator Reasoners
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: '{{url}}'
  title: OpenAPI for NCATS Biomedical Translator Reasoners
  version: 0.9.2
externalDocs:
  description: Documentation for the NCATS Biomedical Translator Reasoners web services
  url: https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI
servers:
- url: /
tags:
- description: Get supported relationships by source and target
  externalDocs:
    description: Documentation for the reasoner predicates function
    url: http://reasonerhost.ncats.io/overview.html#predicates
  name: predicates
- description: Query reasoner using a predefined question type
  externalDocs:
    description: Documentation for the reasoner query function
    url: http://reasonerhost.ncats.io/overview.html#query
  name: query
paths:
  /predicates:
    get:
      operationId: predicates_get
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  additionalProperties:
                    description: Array of predicates
                    items:
                      type: string
                    type: array
                  description: Target map
                  type: object
                description: Source map
                example:
                  chemical_substance:
                    gene:
                    - directly_interacts_with
                    - decreases_activity_of
                type: object
          description: Predicates by source and target
      summary: Get supported relationships by source and target
      tags:
      - predicates
      x-openapi-router-controller: openapi_server.controllers.predicates_controller
  /query:
    post:
      operationId: query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
        description: Query information to be submitted
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: successful operation
        "400":
          description: Invalid status value
      summary: Query reasoner via one of several inputs
      tags:
      - query
      x-swagger-router-controller: swagger_server.controllers.query_controller
      x-openapi-router-controller: openapi_server.controllers.query_controller
components:
  schemas:
    Query:
      additionalProperties: true
      properties:
        message:
          $ref: '#/components/schemas/Message'
      required:
      - message
      type: object
      x-body-name: request_body
    Message:
      additionalProperties: true
      example:
        knowledge_graph:
          nodes:
            key:
              name: Haptoglobin
              type: ""
          edges:
            key:
              target_id: https://www.uniprot.org/uniprot/P00738
              source_id: https://omim.org/entry/603903
              type: affects
        results:
        - edge_bindings:
            key:
            - kg_id: kg_id
            - kg_id: kg_id
          node_bindings:
            key:
            - kg_id: kg_id
            - kg_id: kg_id
        - edge_bindings:
            key:
            - kg_id: kg_id
            - kg_id: kg_id
          node_bindings:
            key:
            - kg_id: kg_id
            - kg_id: kg_id
        query_graph:
          nodes:
            key:
              curie: OMIM:603903
              type: ""
          edges:
            key:
              target_id: https://www.uniprot.org/uniprot/P00738
              source_id: https://omim.org/entry/603903
              type: ""
      properties:
        results:
          description: List of all returned potential answers for the query posed
          items:
            $ref: '#/components/schemas/Result'
          type: array
        query_graph:
          $ref: '#/components/schemas/QueryGraph'
        knowledge_graph:
          $ref: '#/components/schemas/KnowledgeGraph'
      type: object
    Result:
      description: One of potentially several results or answers for a query
      example:
        edge_bindings:
          key:
          - kg_id: kg_id
          - kg_id: kg_id
        node_bindings:
          key:
          - kg_id: kg_id
          - kg_id: kg_id
      properties:
        node_bindings:
          additionalProperties:
            items:
              $ref: '#/components/schemas/NodeBinding'
            type: array
          description: List of QNode-KNode bindings.
          type: object
        edge_bindings:
          additionalProperties:
            items:
              $ref: '#/components/schemas/EdgeBinding'
            type: array
          description: List of QEdge-KEdge bindings.
          type: object
      required:
      - edge_bindings
      - node_bindings
      type: object
    NodeBinding:
      example:
        kg_id: kg_id
      properties:
        kg_id:
          description: A knowledge-graph node id, i.e. the `id` of a KNode
          type: string
      required:
      - kg_id
      type: object
    EdgeBinding:
      example:
        kg_id: kg_id
      properties:
        kg_id:
          description: A knowledge-graph edge id, i.e. the `id` of a KEdge
          type: string
      required:
      - kg_id
      type: object
    KnowledgeGraph:
      additionalProperties: true
      description: A thought graph associated with this result. This will commonly
        be a linear path subgraph from one concept to another, but related items aside
        of the path may be included.
      example:
        nodes:
          key:
            name: Haptoglobin
            type: ""
        edges:
          key:
            target_id: https://www.uniprot.org/uniprot/P00738
            source_id: https://omim.org/entry/603903
            type: affects
      properties:
        nodes:
          additionalProperties:
            $ref: '#/components/schemas/Node'
          description: List of nodes in the KnowledgeGraph
          type: object
        edges:
          additionalProperties:
            $ref: '#/components/schemas/Edge'
          description: List of edges in the KnowledgeGraph
          type: object
      required:
      - edges
      - nodes
      type: object
    QueryGraph:
      additionalProperties: true
      description: A graph intended to be the thought path to be followed by a reasoner
        to answer the question. This graph is a representation of a question.
      example:
        nodes:
          key:
            curie: OMIM:603903
            type: ""
        edges:
          key:
            target_id: https://www.uniprot.org/uniprot/P00738
            source_id: https://omim.org/entry/603903
            type: ""
      properties:
        nodes:
          additionalProperties:
            $ref: '#/components/schemas/QNode'
          description: List of nodes in the QueryGraph
          type: object
        edges:
          additionalProperties:
            $ref: '#/components/schemas/QEdge'
          description: List of edges in the QueryGraph
          type: object
      required:
      - edges
      - nodes
      type: object
    QNode:
      additionalProperties: true
      description: A node in the QueryGraph
      example:
        curie: OMIM:603903
        type: ""
      properties:
        curie:
          description: CURIE identifier for this node
          example: OMIM:603903
          oneOf:
          - type: string
          - items:
              type: string
            type: array
        type:
          oneOf:
          - $ref: '#/components/schemas/BiolinkEntity'
          - items:
              $ref: '#/components/schemas/BiolinkEntity'
            type: array
      type: object
    QEdge:
      additionalProperties: true
      description: An edge in the QueryGraph
      example:
        target_id: https://www.uniprot.org/uniprot/P00738
        source_id: https://omim.org/entry/603903
        type: ""
      properties:
        type:
          oneOf:
          - $ref: '#/components/schemas/BiolinkRelation'
          - items:
              $ref: '#/components/schemas/BiolinkRelation'
            type: array
        source_id:
          description: Corresponds to the @id of source node of this edge
          example: https://omim.org/entry/603903
          type: string
        target_id:
          description: Corresponds to the @id of target node of this edge
          example: https://www.uniprot.org/uniprot/P00738
          type: string
      required:
      - source_id
      - target_id
      type: object
    Node:
      additionalProperties: true
      description: A node in the knowledge graph
      example:
        name: Haptoglobin
        type: ""
      properties:
        name:
          description: Formal name of the entity
          example: Haptoglobin
          type: string
        type:
          oneOf:
          - type: string
          - items:
              $ref: '#/components/schemas/BiolinkEntity'
            type: array
      type: object
    Edge:
      additionalProperties: true
      description: An edge in the thought subgraph linking two nodes
      example:
        target_id: https://www.uniprot.org/uniprot/P00738
        source_id: https://omim.org/entry/603903
        type: affects
      properties:
        type:
          description: A relation, i.e. child of related_to (snake_case)
          example: affects
          externalDocs:
            description: Biolink model relations
            url: https://biolink.github.io/biolink-model/docs/related_to.html
          type: string
        source_id:
          description: Corresponds to the @id of source node of this edge
          example: https://omim.org/entry/603903
          type: string
        target_id:
          description: Corresponds to the @id of target node of this edge
          example: https://www.uniprot.org/uniprot/P00738
          type: string
      required:
      - source_id
      - target_id
      type: object
    BiolinkEntity:
      description: A subclass of category named_thing (snake_case)
      example: disease
      externalDocs:
        description: Biolink model entities
        url: https://biolink.github.io/biolink-model/docs/NamedThing.html
      type: string
    BiolinkRelation:
      description: A relation, i.e. child of related_to (snake_case)
      example: affects
      externalDocs:
        description: Biolink model relations
        url: https://biolink.github.io/biolink-model/docs/related_to.html
      type: string
